Small fixes and ops v2 ready for public
blockchain-insights/blockchain-data-subnet-ops pull request #27
Opened 2024-03-06 21:06 UTC by cornbread-998

2024-03-06 21:14 UTC, aph5nt requested changes

2024-03-06 21:14 UTC, aph5nt commented on .gitignore
> +.env
remove it pls, when i do git pull on server i need to stash that file as i can not pull

2024-03-06 22:27 UTC, ronnie-samaroo approved these changes

2024-03-07 08:57 UTC, cornbread-998 commented on .gitignore
> +.env
its actually the opposite, without .gitignore .env file edits need to be stashed, no?

2024-03-07 09:21 UTC, merged